name: Node.js CI and Deploy (Peaceiris)

on:
  push:
    branches: [src]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies for gulp-image-resize
        run: sudo apt update && sudo apt install -y imagemagick graphicsmagick

      - name: Install package dependencies
        run: npm ci

      - name: Run build.js
        run: node build.js

      - name: Run npm build
        run: npm run build
      - name: Check build output
        run: ls -R dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: master
          cname: scist.org
